### ISSUE TITLE
'CaptainHook.h' file not found？

### ISSUE THREAD

**Issue by MasterBetter** [chaserr/WeChatDemo#1]
请问这个怎么处理？

**Comment by chaserr** [comment]
没有安装theos环境？

**Comment by chaserr** [comment]
@NOMBER2011 没有安装theos环境？

**Comment by MasterBetter** [comment]
我没安装，我是第一次看这中逆向工程的，小白一个，安装之后是不是将手机就越狱了

**Comment by chaserr** [comment]
@NOMBER2011 不是，在你电脑上安装，具体可以goooog -- theos环境安装，然后使用自己的个人的免费证书（7天过期）就可以运行在自己的手机。当然付费的就更好了

**Comment by MasterBetter** [comment]
好的，谢谢了

**Comment by MasterBetter** [comment]
我现在把这个安装好了，我下来怎么操作？QQ：564811383，可否教我下，谢谢了
